#!/usr/bin/env bash

domain=$1
subdomain=$2

if [ -z "$subdomain" ]
then
    query_dns "www" "$domain"
    query_dns "lb-01" "$domain"
    query_dns "web-01" "$domain"
    query_dns "web-02" "$domain"
else
    query_dns "$subdomain" "$domain"
fi
