#!/usr/bin/env bash
#script that will display information about subdomains

domain=$1
subdomain=$2

if [ -z "$subdomain" ]
then
    domain_information "www" "$domain"
    domian_information "lb-01" "$domain"
    domain_information "web-01" "$domain"
    domain_information "web-02" "$domain"
else
    domain_information "$subdomain" "$domain"
fi
