#!/usr/bin/env bash 
#  transfers a file from our client to a server

if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

# Disable strict host key checking for scp
export SCP="scp -o StrictHostKeyChecking=no -i $ssh_key_path"

# Transfer the file to the server's home directory
$SCP $file_path $username@$server_ip:~/

echo "File transferred successfully to $username@$server_ip:~/"

