#!/usr/bin/env bash
# This script displays lines containing the word "bash" to find the PID of your Bash process.
# shellcheck disable=SC2009

# Use ps command to list all processes and filter lines containing "bash"
ps aux | grep "bash"
