#!/usr/bin/env bash
# This script displays numbers and messages based on the loop iteration

i=1

while [ "$i" -le 20 ];
do
	echo $i
	case "$i" in
		4)echo "$i and then bad luck from China";;
		9)echo "$i and then bad luck from Japan";;
		17)echo "$i and then bad luck from Italy";;
    esac

    i=$((i + 1))
done
