#!/bin/env bash
pkill apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i 's/user\s*[^;]*/user nginx/g' /etc/nginx/nginx.conf
sed -i 's/listen\s*[^;]*;/listen 8080/g' /etc/nginx/sites-available/default
service nginx restart
